# Generated by Django 4.0 on 2022-04-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='work_id',
            new_name='work',
        ),
    ]
