# Generated by Django 4.0 on 2022-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0003_rename_user_id_application_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_passed',
            field=models.BooleanField(help_text='合格ならTrue', null=True),
        ),
    ]
