# Generated by Django 4.0 on 2022-04-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0004_application_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
