# Generated by Django 4.0 on 2022-04-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microhr', '0005_application_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microhr.work'),
        ),
    ]
